kind: Secret
apiVersion: v1
metadata:
  name: sealed-secrets-key
data:
  {{- $externalData := .Files.Get "files/certs.yaml" | fromYaml }}
  tls.crt: {{ $externalData.crt | quote }}
  tls.key: {{ $externalData.key | quote }}
type: kubernetes.io/tls
