apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak-deployment
  namespace: openshift-gitops
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: deployment
    repoURL: 'https://github.com/edubois10/keycloak.git'
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true