---
kind: Namespace
apiVersion: v1
metadata:
  name: openshift-gitops
spec:
  finalizers:
    - kubernetes
---
kind: Namespace
apiVersion: v1
metadata:
  name: openshift-gitops-operator
spec:
  finalizers:
    - kubernetes
